# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
!pip install numpy
import numpy as np


In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

print(type(height),height )

print(type(weight),weight )

bmi= weight/(height**2)*730
print(bmi)


<class 'numpy.ndarray'> [69 70 71 72 73 74 75]
<class 'numpy.ndarray'> [110 120 130 140 150 160 170]
[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [22]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

list_1 = [4, 8, 10, 55, 6, 88, 90, 5, 7]
list_2 = [4, 9, 5, 3, 78, 87, 22, 32,  0]
new_list = [list_1, list_2]
print(type(new_list), new_list)
matrixlist=np.array(new_list)
print(type(matrixlist), matrixlist)
print('\nReshape:')
matrixlist=matrixlist.reshape((6, 3))
print(matrixlist)
np.random.uniform(matrixlist)

def makerandomMatrix(list_1, list_2, shape1, shape2):
    new_list = [list_1, list_2]
#     return new_list
    matrixlist= np.array(new_list)
#     return matrixlist
    matrixlist = matrixlist.reshape((shape1, shape2))
#     return matrixlist
  
    return np.random.uniform(matrixlist)
    
print(type(matrixlist),makerandomMatrix(list_1, list_2, 6, 3))




# def makeMatrix(list_1):
#      list_1 = [4, 8, 10, 55, 6, 88, 90, 5, 7]
#      newList = np.array(list_1)
#      return newList
#  print(makeMatrix(list_1))
#  print(type(list_1))


<class 'list'> [[4, 8, 10, 55, 6, 88, 90, 5, 7], [4, 9, 5, 3, 78, 87, 22, 32, 0]]
<class 'numpy.ndarray'> [[ 4  8 10 55  6 88 90  5  7]
 [ 4  9  5  3 78 87 22 32  0]]

Reshape:
[[ 4  8 10]
 [55  6 88]
 [90  5  7]
 [ 4  9  5]
 [ 3 78 87]
 [22 32  0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [ ]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

